spring:
  main.banner-mode: 'off'
  output.ansi.enabled: always
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      poll-interval: 100
      quiet-period: 50
      exclude: static/**,templates/**
---
spring:
  profiles: test
  datasource:
    initialization-mode: never
